apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-application
  labels:
    app: youtube-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-application
  template:
    metadata:
      labels:
        app: youtube-application
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: youtube-application
        image: fadi2000/youtube-application:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
