apiVersion: v1
kind: Service
metadata:
  name: youtube-application
  labels:
    app: youtube-application
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: youtube-application
